# Generated by Django 3.0.2 on 2020-01-14 14:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='medical staff name')),
                ('is_verified', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=30, verbose_name='role in organization')),
                ('speciality', models.CharField(blank=True, default='', max_length=30, verbose_name='medical speciality, if any')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organization.Organization')),
            ],
        ),
    ]
