# Generated by Django 3.0.2 on 2020-01-13 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('medical_staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalstaff',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organization.Organization'),
        ),
    ]
