# Generated by Django 3.0.2 on 2020-01-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_medicalstaff_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='organisation_name',
            field=models.CharField(default='Non-descript', max_length=50, verbose_name='Name of organisation'),
        ),
    ]
